name: CI
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        node: [24.x]
        os: [ubuntu-latest, windows-latest]
        astro: [^5, alpha]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - run: pnpm i --workspace-root astro@${{ matrix.astro }}
      - run: pnpm i astro@${{ matrix.astro }}
        working-directory: packages/astro-auto-import
      - run: pnpm i astro@${{ matrix.astro }} @astrojs/mdx@${{ env.MDX_VERSION }}
        env:
          MDX_VERSION: ${{ matrix.astro == '^5' && '^4' || 'alpha' }}
        working-directory: demo

      - name: Test
        run: pnpm t
